### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest

### ISSUE THREAD

**Issue by daniftodi** [tschaumburg/FastBarcodeScanner#1]
When I call StartCapture() method, applications throws this expcetion:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.hardware.camera2.CaptureRequest$Builder.set(android.hardware.camera2.CaptureRequest$Key, java.lang.Object)' on a null object reference
                                                                              at dk.schaumburgit.stillsequencecamera.StillSequenceCamera2.lockFocus(StillSequenceCamera2.java:630)
                                                                              at dk.schaumburgit.stillsequencecamera.StillSequenceCamera2.StartCapture(StillSequenceCamera2.java:102)
                                                                              at dk.schaumburgit.fastbarcodescanner.FastBarcodeScanner.StartScan(FastBarcodeScanner.java:62)
                                                                              at com.iftodi.dan.qrscanner.MainActivity.btnValidate(MainActivity.java:112)`

**Comment by elliottdehn** [comment]
Yup same thing here. Galaxy S5?

**Comment by DamienDabernat** [comment]
Same here, Galaxy S6

**Comment by tschaumburg** [comment]
Hmm - based on the stack trace it looks like you're running an outdated version. What are you trying to do when this happens - running the demo app? If so, which version, and where did you download it from?

**Comment by saraht129** [comment]
I'm seeing the same error here. I imported the library as modules in my android project, and the simple usage below throws me such error:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_qrcamera);

        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        textureView = (TextureView) findViewById(R.id.texture);

        scanner = new FastBarcodeScanner(QRCameraActivity.this, textureView, 4*1024*768);
    }

    @Override
    protected void onResume() {
        super.onResume();
        scanner.StartScan(false, this, null);
    }
```

**Comment by ErickBergmann** [comment]
It seems you'll need to wait the TextureView to become available before using it. There's a Listener for that:
`TextureView.SurfaceTextureListener`

**Comment by matteotan** [comment]
Hi, has someone solved this issue?
